language: go

go:
  - "1.9"
  - 1.10.x
  - master

matrix:
  fast_finish: true
  allow_failures:
    - go: master

install:
  - go get -u golang.org/x/lint/golint
  
script:
  - go build ./...
  - go test ./...
  - test -z "$(go fmt ./... | tee /dev/stderr)"
  - test -z "$(golint $(go list ./...) | tee /dev/stderr)"
  - go vet ./...
